# Host build (default: gcc)
# Cross-compile for RISC-V CPU example:
#   make CC=riscv32-unknown-elf-gcc CFLAGS_EXTRA="-DNO_DYNAMIC_ALLOC -march=rv32i -mabi=ilp32"

CC          = gcc
CFLAGS      = -O2 -Wall -Wextra -I include -I src -I host -I test/pytorch -I model/fp32 -I model/quant -I train $(CFLAGS_EXTRA)
LDFLAGS     = -lm

TARGET_TRAIN_QUANT  = train_quant
TARGET_CONVERT      = convert_ckpt
TARGET_UT_PYTORCH   = unit_test_pytorch

SRCS_SRC    = src/quant_lut.c \
              src/quant_ops_common.c \
              src/quant_ops_elemwise.c \
              src/quant_ops_relu.c \
              src/quant_ops_pool.c \
              src/quant_ops_conv.c \
              src/quant_ops_linear.c \
              src/quant_ops_softmax.c \
              src/quant_ops_sgd.c \
              src/quant_ops_flatten.c \
              src/quant_ops_hinge.c \
              src/prng.c

SRCS_HOST   = host/qconvert.c \
              host/mnist_loader.c \
              host/fp32_xavier.c \
              host/fp32_ref_alloc.c \
              host/fp32_ref_softmax.c \
              host/fp32_loss_monitor.c

SRCS_MODEL_FP32   = model/fp32/fp32_lenet.c
SRCS_MODEL_QUANT  = model/quant/quant_lenet.c model/quant/quant_lenet_hinge.c model/quant/quant_lenet_w16_dx8_a2.c model/quant/quant_lenet_w16_dx8_convs2fc4.c model/quant/quant_lenet_w16_dx16_a16.c model/quant/quant_lenet_w8_dx8_a8.c model/quant/quant_lenet_w16_dx8_a8.c model/quant/quant_lenet_w16_dx8_a4.c model/quant/quant_lenet_w16_dx16_a16_softmax.c model/quant/quant_lenet_w8_dx8_a8_softmax.c model/quant/quant_lenet_w16_dx8_a8_softmax.c model/quant/quant_lenet_w16_dx8_a4_softmax.c model/quant/quant_lenet_w16_dx8_a2_softmax.c model/quant/quant_lenet_w16_dx8_convs2fc4_softmax.c model/quant/quant_lenet_w16_dx8_convs2ip14tip28.c model/quant/quant_lenet_w16_dx8_convs2ip14tip28_softmax.c model/quant/quant_lenet_w16_dx8_conv12conv24fc4.c model/quant/quant_lenet_w16_dx8_conv12conv24fc4_softmax.c model/quant/quant_lenet_w16_dx4_a4.c model/quant/quant_lenet_w16_dx4_a4_softmax.c model/quant/quant_lenet_w16_dx4_convs2fc4.c model/quant/quant_lenet_w16_dx4_convs2fc4_softmax.c model/quant/quant_lenet_fp32softmax.c

# train/ sources needed by unit_test_pytorch (model_io_quant for checkpoint
# tests, train_common for lenet_weights_init_xavier; train_eval/train_options
# pulled in because train_common.c references symbols from them)
SRCS_TEST_EXTRA = train/model_io_quant.c \
                  train/train_common.c train/train_eval.c train/train_options.c \
                  train/binio.c
OBJS_TEST_EXTRA = $(SRCS_TEST_EXTRA:.c=.o)

SRCS_TEST_PYTORCH = test/pytorch/unit_test.c \
                    test/pytorch/unit_test_softmax_pytorch.c \
                    test/pytorch/unit_test_hinge_pytorch.c \
                    test/pytorch/unit_test_relu_pytorch.c \
                    test/pytorch/unit_test_flatten_pytorch.c \
                    test/pytorch/unit_test_elemwise_pytorch.c \
                    test/pytorch/unit_test_linear_pytorch.c \
                    test/pytorch/unit_test_maxpool_pytorch.c \
                    test/pytorch/unit_test_conv_pytorch.c \
                    test/pytorch/unit_test_onehot_pytorch.c \
                    test/pytorch/unit_test_sgd_pytorch.c \
                    test/pytorch/load_golden.c
OBJS_TEST_PYTORCH = $(SRCS_TEST_PYTORCH:.c=.o)

SRCS_TRAIN_QUANT = train/train_common.c train/train_eval.c train/model_io_quant.c train/binio.c train/train_options.c train/scale_stats.c train/dump_state.c train/dump_raw.c train/train_quant.c train/train_quant_args.c train/train_quant_eval.c train/train_quant_setup.c
OBJS_TRAIN_QUANT = $(SRCS_TRAIN_QUANT:.c=.o)

SRCS_CONVERT = train/convert_checkpoint.c train/binio.c
OBJS_CONVERT = $(SRCS_CONVERT:.c=.o)

OBJS_COMMON = $(SRCS_SRC:.c=.o) $(SRCS_HOST:.c=.o) \
              $(SRCS_MODEL_FP32:.c=.o) $(SRCS_MODEL_QUANT:.c=.o)

# Cross-compile for RISC-V CPU example:
#   make CC=riscv32-unknown-elf-gcc CFLAGS_EXTRA="-DNO_DYNAMIC_ALLOC -march=rv32i -mabi=ilp32" \
#        SRCS="$(SRCS_SRC)"

.PHONY: all clean gen-pytorch-goldens test-pytorch

all: $(TARGET_TRAIN_QUANT) $(TARGET_CONVERT)

$(TARGET_TRAIN_QUANT): $(OBJS_COMMON) $(OBJS_TRAIN_QUANT)
	$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)

$(TARGET_CONVERT): $(OBJS_CONVERT)
	$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)

# --- PyTorch-golden unit tests (Phase 2). Host-only; depends on .bin goldens
# generated by scripts/gen_pytorch_goldens.py. ---
$(TARGET_UT_PYTORCH): $(OBJS_COMMON) $(OBJS_TEST_EXTRA) $(OBJS_TEST_PYTORCH)
	$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)

gen-pytorch-goldens:
	python3 scripts/gen_pytorch_goldens.py

test-pytorch: gen-pytorch-goldens $(TARGET_UT_PYTORCH)
	./$(TARGET_UT_PYTORCH)

%.o: %.c
	$(CC) $(CFLAGS) -c -o $@ $<

clean:
	rm -f $(OBJS_COMMON) $(OBJS_TEST_EXTRA) $(OBJS_TEST_PYTORCH) \
	      $(OBJS_TRAIN_QUANT) $(OBJS_CONVERT) \
	      $(TARGET_TRAIN_QUANT) $(TARGET_CONVERT) $(TARGET_UT_PYTORCH)
